export const EMAIL_REGISTER = "EMAIL_REGISTER";
export const EMAIL_REGISTER_ERROR = "EMAIL_REGISTER_ERROR";
export const ENTERTAINER_BOOKING_INFO = "ENTERTAINER_BOOKING_INFO";
export const LOADING_ENTERTAINER_BOOKING_INFO = "LOADING_ENTERTAINER_BOOKING_INFO";
export const CALANDER_BOOKING_FREE_TIME = "CALANDER_BOOKING_FREE_TIME";
export const CALANDER_BOOKING_NOT_FREE_TIME = "CALANDER_BOOKING_NOT_FREE_TIME";
export const RESULT_SEARCH_TALENTS = "RESULT_SEARCH_TALENTS";
export const ALL_ENTERTAINER_CATEGORY = "ALL_ENTERTAINER_CATEGORY";
export const SUBMIT_COMPLETE_BOOKING = "SUBMIT_COMPLETE_BOOKING";
export const SUBMIT_COMPLETE_BOOKING_FAIL = "SUBMIT_COMPLETE_BOOKING_FAIL";
export const GET_DETAIL_GIG = "GET_DETAIL_GIG";
export const ALL_MY_PAYMENT_METHOD = "ALL_MY_PAYMENT_METHOD";
export const TOTAL_TRAVEL_COST = "TOTAL_TRAVEL_COST";
export const HEARDER_NOTIFICATION = "HEARDER_NOTIFICATION";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const BOOKED_ERROR = "BOOKED_ERROR";
export const GET_ALL_POLICIES="GET_ALL_POLICIES";
export const GET_ALL_PROGRESS_PROFILE = "GET_ALL_PROGRESS_PROFILE";
export const GET_POLICY_DETAIL= "GET_POLICY_DETAIL";
export const CUSTOMER_REVIEW = "CUSTOMER_REVIEW";
export const ENTERTAINER_REVIEW = "ENTERTAINER_REVIEW";
export const GET_COMPLETED_STEPS = "GET_COMPLETED_STEPS";
export const SET_COMPLETED_STEP = "SET_COMPLETED_STEP";
export const GET_ALL_REASONS = "GET_ALL_REASONS";

export default {
  EMAIL_REGISTER,
  EMAIL_REGISTER_ERROR,
  ENTERTAINER_BOOKING_INFO,
  LOADING_ENTERTAINER_BOOKING_INFO,
  CALANDER_BOOKING_FREE_TIME,
  CALANDER_BOOKING_NOT_FREE_TIME,
  RESULT_SEARCH_TALENTS,
  ALL_ENTERTAINER_CATEGORY,
  SUBMIT_COMPLETE_BOOKING,
  SUBMIT_COMPLETE_BOOKING_FAIL,
  GET_DETAIL_GIG,
  ALL_MY_PAYMENT_METHOD,
  TOTAL_TRAVEL_COST,
  HEARDER_NOTIFICATION,
  UPDATE_BOOK_SUCCESS,
  BOOKED_ERROR,
  GET_ALL_POLICIES,
  GET_ALL_PROGRESS_PROFILE,
  GET_POLICY_DETAIL,
  CUSTOMER_REVIEW,
  ENTERTAINER_REVIEW,
  GET_COMPLETED_STEPS,
  SET_COMPLETED_STEP,
  GET_ALL_REASONS,
}